---
:tddium:
  :ruby_version: ruby-1.9.3-p547
  :bundler_version: 1.5.3
  :mysql:
    :version: '5.6'
  :sqlite: false
  :hooks:
    :worker_setup: RAILS_ENV=test bundle exec rake db:migrate
  :rabbitmq: true
  :test_pattern:
    - spec/**_spec.rb
  :timeout_hook: 1200
